version: '3'
services:
  wim:
    build: ./wim-nbi
    image: wim-nbi
    container_name: wim-nbi
    command: >
      gunicorn -b 0.0.0.0:3000
        --access-logfile -
        --reload
        "wim.app:create_app()"
    ports:
     - "3000:3000"
    restart: always
    volumes:
      - "./wim-nbi:/wim-nbi"
  # mongo:
  #   image: mongo:latest
  #   restart: always
